/**
 * migrate.ts — Transform exported Supabase data and generate D1-compatible SQL
 *
 * Usage: npx tsx scripts/migrate.ts
 *
 * Reads from: scripts/data/{table}.json (created by export-supabase.ts)
 * Outputs to: scripts/data/migrate.sql
 *
 * Then import with:
 *   wrangler d1 execute DB --file=scripts/data/migrate.sql
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, 'data');
const OUTPUT_FILE = join(DATA_DIR, 'migrate.sql');

// FK-ordered insert sequence
const INSERT_ORDER = [
  'categories',      // no deps
  'site_content',    // no deps
  'gear_hardware',   // no deps
  'gear_software',   // no deps
  'gear_hobbies',    // no deps
  'gear_projects',   // no deps
  'gear_podcasts',   // no deps
  'links',           // depends on categories (FK)
  'collections',     // logically after links
];

function escapeSQL(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (Array.isArray(value)) return `'${escapeSQLString(JSON.stringify(value))}'`;
  return `'${escapeSQLString(String(value))}'`;
}

function escapeSQLString(str: string): string {
  return str.replace(/'/g, "''");
}

// Column mappings per table — defines which columns to insert and in what order
const TABLE_COLUMNS: Record<string, string[]> = {
  categories: ['name', 'sort_order'],
  site_content: ['id', 'content', 'updated_at'],
  gear_hardware: ['id', 'name', 'badge', 'image_url', 'url', 'description', 'sort_order'],
  gear_software: ['id', 'name', 'badge', 'icon', 'url', 'description', 'sort_order'],
  gear_hobbies: ['id', 'name', 'badge', 'image_url', 'url', 'description', 'sort_order'],
  gear_projects: ['id', 'name', 'badge', 'icon', 'url', 'description', 'sort_order'],
  gear_podcasts: ['id', 'name', 'author', 'artwork_url', 'apple_url', 'url', 'description', 'sort_order'],
  links: ['id', 'url', 'title', 'description', 'image', 'favicon', 'domain', 'category', 'tags', 'stars', 'note', 'summary', 'status', 'read', 'private', 'saved_at'],
  collections: ['id', 'recipient', 'message', 'link_ids', 'created_at'],
};

interface RowData {
  [key: string]: unknown;
}

function transformRow(table: string, row: RowData): RowData {
  const transformed = { ...row };

  if (table === 'links') {
    // Boolean → integer conversion
    transformed.read = row.read ? 1 : 0;
    transformed.private = row.private ? 1 : 0;

    // Ensure stars is a number
    if (typeof transformed.stars !== 'number') {
      transformed.stars = Number(transformed.stars) || 0;
    }
  }

  if (table === 'collections') {
    // Ensure link_ids is a JSON string
    if (Array.isArray(row.link_ids)) {
      transformed.link_ids = JSON.stringify(row.link_ids);
    }
  }

  return transformed;
}

function generateInsert(table: string, columns: string[], row: RowData): string {
  const values = columns.map((col) => escapeSQL(row[col]));
  return `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values.join(', ')});`;
}

function main(): void {
  console.log('Generating D1 migration SQL...');
  console.log('');

  const sqlLines: string[] = [
    '-- D1 Migration SQL',
    '-- Generated by scripts/migrate.ts',
    `-- Date: ${new Date().toISOString()}`,
    '',
    '-- Ensure schema exists first:',
    '-- wrangler d1 execute DB --file=src/db/schema.sql',
    '',
  ];

  const counts: Record<string, number> = {};
  let totalRows = 0;

  for (const table of INSERT_ORDER) {
    const filePath = join(DATA_DIR, `${table}.json`);
    const columns = TABLE_COLUMNS[table];

    if (!columns) {
      console.warn(`  ${table}: No column mapping defined, skipping`);
      continue;
    }

    if (!existsSync(filePath)) {
      console.warn(`  ${table}: No data file found (${filePath}), skipping`);
      counts[table] = 0;
      continue;
    }

    const raw = readFileSync(filePath, 'utf-8');
    const rows = JSON.parse(raw) as RowData[];
    counts[table] = rows.length;
    totalRows += rows.length;

    sqlLines.push(`-- ${table} (${rows.length} rows)`);

    for (const row of rows) {
      const transformed = transformRow(table, row);
      sqlLines.push(generateInsert(table, columns, transformed));
    }

    sqlLines.push('');
    console.log(`  ${table}: ${rows.length} rows`);
  }

  // Verification queries
  sqlLines.push('-- Verification: run these queries to check row counts');
  for (const table of INSERT_ORDER) {
    sqlLines.push(`-- SELECT '${table}' AS tbl, COUNT(*) AS cnt FROM ${table};`);
  }

  writeFileSync(OUTPUT_FILE, sqlLines.join('\n'));

  console.log('');
  console.log(`Total: ${totalRows} rows`);
  console.log(`Output: ${OUTPUT_FILE}`);
  console.log('');
  console.log('To import:');
  console.log('  1. Create schema: wrangler d1 execute DB --file=src/db/schema.sql');
  console.log('  2. Import data:   wrangler d1 execute DB --file=scripts/data/migrate.sql');
  console.log('');

  // Verification summary
  console.log('Expected row counts:');
  for (const [table, count] of Object.entries(counts)) {
    console.log(`  ${table}: ${count}`);
  }
}

main();
